### ISSUE TITLE
Discussion: Change this repo to live under `/near/` rather than `/nearprotocol/`

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/NEPs#135]
I had the hardest time finding out NEAR had NEPs!
As a dev I want to see the direction and work the community is doing.
NEP repo is missing from the main OSS near org, and also missing links on the main near.org website so this repo is hard to find. 
I think it should be possible to do, will take a little bit of help notifying previous PR owners of this change.

**Comment by bowenwang1996** [comment]
Done
