### ISSUE TITLE
Document order of triggers when a block is applied

### ISSUE THREAD

**Issue by bowenwang1996** [near/NEPs#191]
We should document events that lead to account state change when a block is applied and the order of those events. https://github.com/near/near-indexer-for-explorer/issues/77#issuecomment-812575249

**Comment by telezhnaya** [comment]
I need this in my work. While reading the code, I got this order:
1. ValidatorAccountsUpdate
2. Migration
3. TransactionProcessing
4. ActionReceiptProcessingStarted
5. ReceiptProcessing
6. ActionReceiptGasReward
7. PostponedReceipt
8. UpdatedDelayedReceipts

Could you please approve/correct that?

**Comment by EgorKulikov** [comment]
I will add this documentation shortly, for the time being you can refer to [this](https://docs.google.com/spreadsheets/d/1rDLvIp4tot3tjtSXoBNvi5_7N4SSyCAihF2-GwHJKKU/edit?usp=sharing)

Note that in your list stages of applying chunk are mixed with stages of processing of single receipt

**Comment by bowenwang1996** [comment]
Addressed in #223
