### ISSUE TITLE
Implement a retrieval of block info host function

### ISSUE THREAD

**Issue by ilblackdragon** [near/NEPs#208]
There are at least a few use cases to use information about blockchain itself inside a smart contract.

The simplest example is to verify that some information was included in the blockchain some time ago via a merkle proof.
To do this verification, a look back for a block's info is required. Example [voting with staked NEAR](https://gov.near.org/t/use-staked-near-in-sputnik-v2/2354).

A simple `block_hash(index)` would be a good start. It's fine it only works for 3 epochs that we guarantee data availability. It can fail or return None if index is under or over the available blocks. To use it for data inclusion verification, a verification of `BlockHashLite` will be required similar to Rainbow Bridge + all chunk state roots to verify inclusion in `block_merkle_root`.

A more comprehensive function that returns chunk hashs and other info might be interesting. This would require defining a more concrete format that won't change in the future which might be complex. It can be just `BlockHashLite`.

**Comment by nearmax** [comment]
It is sufficient for the contract to have access to the current block hash to verify anything in the past.

State verification, transaction inclusion verification, and outcome/logs verification like that in Rainbow bridge require the contract to be a given a merkle path to state node/transaction/outcome/logs anyway (which includes merkle paths inside chunks, and to the chunks). So by providing access to block hashes of past blocks we are only saving contracts from not needing a merkle path from the current block hash to the previous block hashes, which is a micro-optimization IMO. Besides, by limiting it to 3 epochs we are adding complexity to any contract that will rely on such host function (e.g. there is going to be an expiration mechanism which all contracts would have to take care of).

**Comment by nearmax** [comment]
Continuing the conversation here https://near.zulipchat.com/#narrow/stream/295558-dev-protocol-core/topic/block.20hashes.20host.20func/near/248687577

**Comment by bowenwang1996** [comment]
Looks like Aurora does not really need this functionality at the moment. I think we should close this issue for now and reopen if there is some strong reason to do so
