### ISSUE TITLE
Document that refunds are free

### ISSUE THREAD

**Issue by bowenwang1996** [near/NEPs#211]
https://github.com/near/NEPs/blob/master/specs/RuntimeSpec/Refunds.md does not mention the cost of refund at all, which could be confusing. Refunds are special in that they have a gas price of 0 and they don't contribute to burnt gas (gas free). This should be documented.

**Comment by mzhangmzz** [comment]
I think it is already mentioned in the page, but maybe it is not obvious. I made some changes to the current description.
