### ISSUE TITLE
Nomicon shuffles contents

### ISSUE THREAD

**Issue by telezhnaya** [near/NEPs#214]
Not sure if it's the right place to report. 

https://nomicon.io/Standards/README.html
<img width="1351" alt="Screenshot 2021-06-11 at 14 48 11" src="https://user-images.githubusercontent.com/11246099/121682255-8644f900-cac4-11eb-8b5d-26d39794dfc6.png">

By the way, it's good to add the possibility to contribute to Nomicon somehow. Now it's unclear how to do that. 
https://docs.near.org looks awesome with `Edit` button everywhere. It costs nothing to fix a typo there.

**Comment by bowenwang1996** [comment]
Transferred the issue to this repo
