### ISSUE TITLE
Add spec for epoch transition

### ISSUE THREAD

**Issue by mzhangmzz** [near/NEPs#248]
How genesis block, epoch are generated, 
how information on new epoch is determined,
etc.

**Comment by bowenwang1996** [comment]
@mzhangmzz could you point out what is missing in https://github.com/near/NEPs/tree/master/specs/BlockchainLayer/EpochManager ?

**Comment by mzhangmzz** [comment]
Ah yeah, that's what I wanted. I just didn't see it in nomicon.io.

**Comment by bowenwang1996** [comment]
I see. Looks like we can close this issue then
