### ISSUE TITLE
NEP 171 (NFT) links to ft_* methods, has no minting/burning info

### ISSUE THREAD

**Issue by telezhnaya** [near/NEPs#250]
Try to `ctrl + F` `ft_` in NFT interface section
https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Core.md#nft-interface
You could see 6 places where we require `ft_*` methods inside NFT implementation. That sounds weird. I thought FT and NFT are separate standards.

@mikedotexe @chadoh @evgenykuzyakov is it a typo?

Another question: I didn't find a place where we document the process of minting NFTs. I see that some implementations have the following methods
```
"nft_mint"
"nft_mint_for"
"nft_bulk_mint_for"
"nft_drop_mint_for"
```
But I see nothing about it in NEP. Maybe we should add something about it?

And, finally. What should we do if we want to burn NFT?

**Comment by chadoh** [comment]
@mattlockyer @willemneal I know you've both been working with NFT projects lately. Do either of you have a sense of a de facto approach for minting/burning NFTs? Or a suggestion for @telezhnaya about how you think it should be done?

**Comment by willemneal** [comment]
Minting should documented.  I discovered through trial and error that the current `nft_mint` provided by the standard only allows the owner of the NFT contract to mint, however, I'm my application and others this won't be the case. So we should at least have different options about what to expect with a `nft_*mint*`.

**Comment by zcstarr** [comment]
> either
@chadoh yep we discussed events as well, we think events would be the right way to handle this, but the timeline for events seemed perhaps a ways off.  The stop gap for the multi token standard is to do things like have methods for determining supply in the standard and follow the function naming convention. 

Binary events I think really is the long term solution to tracking things like minting and transfers. I think @MaximusHaximus 
mentioned that events would also solve some ordering issues that wallet has with regards to transfers.

With regards to minting, I'm all for not having minting in the standard as well.

**Comment by telezhnaya** [comment]
I don't have a solid opinion on how it should be implemented.
But, I want to have a clear understanding, who owns the tokens, how much, when, why.
With our NEPs, I can track all transfers, but I can't track minting/burning in any way. 
So it's impossible to make any assumptions about FT/NFT. 

It means that we can't fully support FT/NFT in [Explorer](https://explorer.near.org), [Wallet](https://wallet.near.org), and other (including 3rd-party) tools.

**Comment by telezhnaya** [comment]
Close this issue since docs are fixed, will reopen separate issue about minting/burning
