### ISSUE TITLE
FT NEP-141 require having minting/burning interface

### ISSUE THREAD

**Issue by telezhnaya** [near/NEPs#271]
We finished the work on support of NFT https://github.com/near/NEPs/issues/254 https://github.com/near/NEPs/issues/256 :tada:
It's better to read [NFT events standard](https://nomicon.io/Standards/NonFungibleToken/Event.html) at first, since we want to do the pretty same thing for FTs.
Current FT doc: https://nomicon.io/Standards/FungibleToken/README.html

Some initial thoughts:
- The work here should go much easier, we can take the same approach as in FTs: we use logs to imitate the events.
- For one smart contract, we have at most one FT associated with it. Is it true? If so, we don't need to pass `token_id`. UPD: no, it's not true for MultiToken standard. So we have to pass `token_id` even in a simple FT contract.
- We have the new field: `amount`, it should be provided in the highest precision for each smart contract.
- We need to re-check that we don't have any fees in FT. If Alice transfers 1 FT to Bob, it means that Alice spent exactly 1 FT (and the fee in NEAR, we don't need to think about it, it's not on the smart contract abstraction layer), Bob received exactly 1 FT.
- We still have 3 types of actions: `mint`, `burn` and `transfer`.
- We still have optional `memo` field.
- We don't need to add `msg` field, it's technical field for supporting cross-contract calls, we don't care about that.
- We don't have the support of approval management for FT ([approvals in NFT](https://nomicon.io/Standards/NonFungibleToken/ApprovalManagement.html)), we even don't have the issue about that, but I've heard we want such functionality. Should we think about approvals at first?
- Do we need batch events? Should we use batch syntax (read: arrays in all places where possible) just because we can?

@mikedotexe I know it's not your war anymore, but if you are ready to participate in any role, you are more than welcome ❤️ 

@jberrytech @frol @MaximusHaximus 
Please tag anyone else who could be interested. Especially I want FT contract developers to be involved

**Comment by frol** [comment]
cc all subscribers to this issue, please review https://github.com/near/NEPs/pull/300
