### ISSUE TITLE
Nomicon does not get the latest update

### ISSUE THREAD

**Issue by telezhnaya** [near/NEPs#310]
I've added the point in contents #309, but it does not appear in the right bar on Nomicon.

Also, the contents exists, but we have 404 here
https://nomicon.io/Standards/EventsFormat.html
https://github.com/near/NEPs/blob/master/specs/Standards/EventsFormat.md

**Comment by bucanero** [comment]
hello @telezhnaya,

We have recently migrated Nomicon to Docusaurus. The URL paths should be similar, but Docusaurus doesn't use the `.html` extension. So in this case, the new URL is:
- `https://nomicon.io/Standards/EventsFormat.html` -> https://nomicon.io/Standards/EventsFormat

If needed, I can try to add redirects so all the `*.html` links go to the new URLs. Let me know 😄

**Comment by bucanero** [comment]
Update: I have added some server-side redirect instructions. Now, `EventsFormat.html` should redirect to `EventsFormat`, but please let me know if you find any other issues. 👍

**Comment by telezhnaya** [comment]
Works fine now
Thank you!
