### ISSUE TITLE
Events or there alternative? Getting notified when coins have arrived to a contract

### ISSUE THREAD

**Issue by GildedHonour** [near/NEPs#403]
I have a smart contract with a `payable` method. I want to somehow get notified when coins has gotten sent to it. How to do it given that there're no Events in NEAR? 

I've found this - https://nomicon.io/Standards/EventsFormat

But is this specific to NFTs only?

If not, how would I then make use of those `log!(....)`s? Where would I, in a smart contract, see them?

If it is, would I instead have to poll the `balance` field of my contract every minute and would this be the only way? Also, making calls to a contract isn't free for it requires gas, huh?

**Comment by frol** [comment]
See https://github.com/near/near-sdk-rs/pull/934

**Comment by GildedHonour** [comment]
A PR what's WIP and closed. Not even merged. How's that supposed to help me Frol @frol ?

**Comment by frol** [comment]
> I want to somehow get notified when coins has gotten sent to it.

What do you mean by that? Do you want to have a telegram message / webhook / function call on the chain? Who do you want to pay for it?

> I've found this - https://nomicon.io/Standards/EventsFormat. But is this specific to NFTs only?

No, it is not specific to NFT, it is also used in FT and MT standards and you are free to use them as well. Just follow the standard.

> A PR that's a) WIP and b) closed. 

Which one is closed? It is a pretty recent PR that addresses exactly your question:

> If not, how would I then make use of those `log!(....)`s?

And then regarding:

> Where would I, in a smart contract, see them?

Do you control the contract that emits the logs? If so (if it is your contract), you don't need to "see" when the logs are emitted, just write the code that does something before emitting the log/event.

> If it is, would I instead have to poll the balance field of my contract every minute and would this be the only way?

If you need to observe something off-chain, you can use [Pagoda Alerts](https://console.pagoda.co/alerts) for webhooks or [build your own indexer based on, e.g. NEAR Lake](https://near-indexers.io/docs/projects/near-lake-framework) (don't miss the "Tutorials" link)

> Also, making calls to a contract isn't free for it requires gas, huh?

If you call view-only functions, you don't need to submit a transaction, that is free of charge right now as it is served directly by the RPC server.

**Comment by GildedHonour** [comment]
You had given the advice first, and now you're asking what I really meant. Backwards.


>Do you control the contract that emits the logs? If so (if it is your contract), you don't need to "see" when the logs are emitted, just write the code that does something before emitting the log/event.

"**I have** a smart contract".  

> just write the code that does something before emitting the log/event."

What if I need "write code that does something" which is to update a table in  database on my VPS server? This would work very well from a smart contract.


>If you call view-only functions, you don't need to submit a transaction, that is free of charge right now as it is served directly by the RPC server.

Yes, it's a view function - "get balance by user_id".
That's good. Where is this described?

**Comment by frol** [comment]
> You had given the advice first, and now you're asking what I really meant.

Sorry, I was of a better opinion of you as I saw you found Events Standard. That is why I suggested you some follow up links.

If you want to continue conversation, mind your tone, the community is not your slaves.

**Comment by frol** [comment]
> "I have a smart contract" as it's written in my 1st post.

You can have whatever contract which does not necessarily FT contract which is why I asked: “Do you control the contract that emits the logs?”

> What if I need "write code that does something" which is to update a table in database on my VPS server? This would work very well from a smart contract.

Smart contracts operate in the excitement that has to be reproducible no matter when and where you call them (even 100 years from now from another planet), which is why smart contracts cannot access external resources like external database. Thus, you need to observe the blockchain changes from outside of the chain, e.g. using Pagoda Alerts or NEAR Indexer Framework or NEAR Lake Framework.

> Where is this described?

In the docs: https://docs.near.org

> What is it "right now"? Is it subject to become paid in the future?

In decentralized world all the parties should be incentivized by design, so yes, it should be expected to use some provider or run and maintain your own node

**Comment by GildedHonour** [comment]
>Sorry, I was of a better opinion of you as I saw you found Events Standard.

Nooooo man.... 
You should always think of me as worst as you can. And even then, divide that by 3.

Better luck next time.
