### ISSUE TITLE
The Type of receipt_id

### ISSUE THREAD

**Issue by zlog-in** [near/NEPs#405]
Hello,

It seems that the type of `receipt_id` denoted as `AccoutID` [here](https://github.com/near/NEPs/blob/master/specs/RuntimeSpec/Receipts.md#receipt_id) is wrong, the results showed in [Near explorer](https://explorer.testnet.near.org/transactions/9WkD1GFGmWntX8ZN6WLHXFM81FUWMRgMm8zfy8dTRpXP) is like a crypto hash value.

```
Receipt ID: GxLimMPC9iZYu35EJt8BptdbmgbqwaXF7r5K23QTUPr9
```

Is `CryptoHash` the right one?

**Comment by frol** [comment]
Yes, it should be CryptoHash. Fixed in #409
