### ISSUE TITLE
Confusing use of "subject matter experts" in NEP-001

### ISSUE THREAD

**Issue by akhi3030** [near/NEPs#464]
The phrase "subject matter experts" is used in different parts of NEP-001, e.g. [here](https://github.com/near/NEPs/blob/master/neps/nep-0001.md?plain=1#L27) and [here](https://github.com/near/NEPs/blob/master/neps/nep-0001.md?plain=1#L69).

Based on my understanding, the same phrase is being used to describe two different sets of people.  This can cause some confusion as seen in this [zulip thread](https://near.zulipchat.com/#narrow/stream/345766-pagoda.2Fstorage.2Fflat-storage/topic/NEP/near/338309740).  If my understanding is correct, I propose that we use different terms to describe the above two sets of people to avoid this confusion.

**Comment by frol** [comment]
@akhi3030 Good catch! Indeed, we should fix the first occurrence as those are work group members who were selected.
