### ISSUE TITLE
Write a spec for chain syncing

### ISSUE THREAD

**Issue by SkidanovAlex** [near/NEPs#48]
The corresponding review work item is here: https://github.com/nearprotocol/nearcore/issues/2307

Write a spec for all the chain sync modes.

We have three modes of syncing: header syncing, block syncing and state syncing.

The entry point for any sync-related logic is `ClientActor::sync`. This method is called every few milliseconds. It checks whether any syncing is needed, and if any needed, delegates the actual work to `HeaderSync`, `BlockSync`, or `StateSync` classes.

## HeaderSync

We switch to HeaderSync if one of our peers claims to have their head way ahead of ours (in terms of height).

Since peers can provide arbitrary value, this is a vector for a possible attack. We somewhat circumvent it by monitoring how quickly a particular peer sends us the headers, and if it's too slow, we ban them and therefore remove their reported head from consideration when deciding again whether to do header sync.

Header sync starts by us sending several anchor hashes (so called "locator"), and the responding side starts sending us headers starting from the most recent anchor hash that is on the canonical chain.

## BlockSync

I don't know exactly how BlockSync work, so that will have to be mostly picked up from code.

## StateSync

StateSync constitutes sending sufficient information for the recipient to start processing and building the chain without downloading and processing all the blocks. The state sync consists of 

TODO: @Alex Kouprin can you write a quick overview of all the components of StateSync with their location in the code

State Sync is a procedure which allows a node to receive the State from another node without processing all blocks. For our particular purpose, State can be described as Trie of raw data.

The circumstances of when State Sync should run are outside of State Sync and not needed for its understanding at this point. State Sync executing starts with calling `StateSync::run`. It takes `sync_hash` - a hash of the first block of the new epoch. `sync_hash` means that we want to receive complete state strictly before Block with hash `sync_hash`.

State Sync may request States for several shards. They are in `tracked_shards`.

In State Sync, the State for concrete shard is divided into two concepts:

1. State Header, which has important data to make syncing possible. It contains latest chunk, incoming receipts, proofs and metadata about State - `StateRootNode`.
2. State Parts, filled with raw data. We assume that:
    1. There are reasonable number of parts. Each part is no more than 1 Mb long.
    2. Parts can be validated and stored easily (check `validate_state_part()`).
    3. Parts can be combined easily to receive the complete State. All the Parts are needed to get the State (check `confirm_state()`).

According to described above, for each shard State Sync status is stored at `ShardSyncStatus` and may be the following:

1. StateDownloadHeader - we want to get State Header.
2. StateDownloadParts - we want to get State Parts.
3. StateDownloadFinalize - we received all parts and want to combine them together.
4. StateDownloadComplete - we've done everything properly, no action is needed.

### Getting State Header

To get State Header, State Sync sends `NetworkRequests::StateRequestHeader` to the node which has the State for the shard. A node who received the request calls `get_state_response_header()`, calculates it locally and returns `ShardStateSyncResponseHeader` by sending `NetworkViewClientResponses::StateResponse` back.

The code of `get_state_response_header()` is hard to understand without paper and pen, that's why you may find lots of comments there. The idea is, everything which is not stored at State should be proven firmly. At `get_state_response_header()` we build proofs to check them later by node who requests the State.

`state_root_node` is important one to continue State Sync. It contains knowledge of State Size, which is necessary to dividing State into State Parts, and State Hash, which is necessary to prove State Parts later.

A node, who receives State Header, executes `set_state_header()` to make sure that the State Header is correct. It runs all checks and proves State Header validity.

### Getting State Part

After receiving valid and proven State Header, a node is able to request State Parts by sending `NetworkRequests::StateRequestPart`. A node who received the request calls `get_state_response_part()` and returns `Vec<u8>` of Part by sending `NetworkViewClientResponses::StateResponse` back.

`get_state_response_part()` delegates collecting of State Part to Trie by calling `obtain_state_part()`.

A node, who receives State Parts, executes `set_state_part()` for each of it. `set_state_part()` delegates all proofs to Trie by calling `validate_state_part()` and store the State Part in storage.

### Finalizing

After getting all State Parts, a node is unlocked to call `set_state_finalize()`. It runs last checks that the Complete State matches to all State Parts collected together and replaces the current State with the State we just received. All parts are deleted then by calling `clear_downloaded_parts()`.

**Comment by nearmax** [comment]
@mfornet estimated that it would take him about 2 weeks to spec it out. Assigning estimate of 10.

**Comment by bowenwang1996** [comment]
It seems that this issue refers to the spec of the current syncing whereas @mfornet will be working on the new syncing spec.

**Comment by bowenwang1996** [comment]
Close this since we are going to rebuild syncing, which is tracked in https://github.com/near/nearcore/issues/3776
