### ISSUE TITLE
relayer callback

### ISSUE THREAD

**Issue by bhc8521** [near/NEPs#487]
is there a way to call back on relayer's contract to calculate the gas after the relayer has sent a delegate action?

**Comment by frol** [comment]
@bhc8521 It is not the relevant place to seek the answer. I can recommend asking either on the relayer server implementation repo: https://github.com/near/pagoda-relayer-rs, or [on StackOverflow with `nearprotocol` tag](https://stackoverflow.com/questions/tagged/nearprotocol).
