### ISSUE TITLE
Bounty: 

### ISSUE THREAD

**Issue by rusdee09** [near/NEPs#557]
### What talent are you looking for?

Marketing

### Currency

USDC.e

### KYC

- [X] Use KYC Verification

**Comment by mfornet** [comment]
Bounties don't belong to this repository. They used to belong to [near/bounties](https://github.com/near/bounties) (see [comment](https://github.com/near/community/issues/12#issuecomment-634653476)) and now the belong to [Gigs Board](https://near.social/mob.near/widget/MyPage?accountId=devgovgigs.near). 

Moreover, there is no actionable information on this issue. (It says "marketing")

I see that this template is suggested when opening an issue on this repository with the name Simple Bounty. Should we remove it or explain how to use it?

I'm closing this issue for now.
