### ISSUE TITLE
Explain what Simple Bounty template is for

### ISSUE THREAD

**Issue by mfornet** [near/NEPs#561]
I recently closed Issues #553, #558, #559, and #560 due to a need for more information or actionable items. They were all using the Simple Bounty template, which is suggested at the top when creating an Issue on this repository. I can't find when or why the template was created.

Should those closed issues be re-opened? Should we add some documentation on how to use this template?

**Comment by frol** [comment]
I think those were created through https://www.heroes.build/, but I also don't understand what is going on there :-(

**Comment by mfornet** [comment]
We can at least remove the template from the new issue view. We can check how to block/auto-close the new issues if they keep coming.
