### ISSUE TITLE
Rewards mismatch between spec and code

### ISSUE THREAD

**Issue by mikhailOK** [near/NEPs#66]
1.
```
`epochFee[t]` | `sum([(1 - DEVELOPER_PCT_PER_YEAR) * txFee[i]])`, where [i] represents any considered block within the epoch[t]
```
leftovers from old spec?

2.
```
Total reward every epoch t is equal to:

reward[t] = totalSupply * ((1 + REWARD_PCT_PER_YEAR) ** (1 / EPOCHS_A_YEAR) - 1)
```
vs
```
        let epoch_total_reward = (U256::from(*self.max_inflation_rate.numer() as u64)
            * U256::from(total_supply)
            * U256::from(self.epoch_length)
            / (U256::from(self.num_blocks_per_year)
                * U256::from(*self.max_inflation_rate.denom() as u64)))
        .as_u128();
```
- REWARD_PCT_PER_YEAR is replaced with max_inflation_rate fraction it seems
- EPOCHS_A_YEAR -> `this_epoch_length / num_blocks_per_year`
- this is an intermediate value in computation but seems like it's supposed to round down? should be `floor(...)`
- `total_supply` - where does this come from? Seems like it's the `total_supply` from the header of last block, however that's computed.

3. What's happening with treasury cut of the reward?

**Comment by bowenwang1996** [comment]
> REWARD_PCT_PER_YEAR is replaced with max_inflation_rate fraction it seems

Yes. Are you referring to the inconsistency in naming?

> EPOCHS_A_YEAR -> this_epoch_length / num_blocks_per_year

Is there a problem with this?

> this is an intermediate value in computation but seems like it's supposed to round down? should be floor(...)

Not sure what you mean here but it seems that it's already rounded down.

> total_supply - where does this come from? Seems like it's the total_supply from the header of last block, however that's computed.

Yes. Where's the inconsistency?

> What's happening with treasury cut of the reward?

Computed right now the next line
```
let epoch_protocol_treasury = (U256::from(epoch_total_reward)
            * U256::from(*self.protocol_reward_percentage.numer() as u64)
            / U256::from(*self.protocol_reward_percentage.denom() as u64))
        .as_u128();
```

**Comment by mikhailOK** [comment]
regarding REWARD_PCT_PER_YEAR, EPOCHS_A_YEAR, total_supply:
Spec can't refer to parameters that aren't defined anywhere. It should refer to genesis config (epoch_length, num_blocks_per_year), or other parts of the spec that define how they are computed (total_supply)

>Not sure what you mean here but it seems that it's already rounded down.

- It is rounded down in the code by virtue of uint256 division operation
- It is not rounded down in the spec: other things like `pct_online[t][j]` are not rounded

>Computed right on the next line

- Computed in the code, subtracted from total epoch reward, the rest is used for validator rewards
- None of this is matches the spec

**Comment by ilblackdragon** [comment]
Seems like straighforward update @mikhailOK - feel free to do it.
