### ISSUE TITLE
Improve number of seats calculation

### ISSUE THREAD

**Issue by ilblackdragon** [near/NEPs#76]
Currently we have 100 seats for block producers. 100 is coming from performance of the consensus not economic parameters, where we are targeting 100 unique block producers.

But currently the way we fill in the seats is done via economics, e.g. if some validator has 10x of others the stake - they will have 10 the seats. Meaning that total number of unique block producers will be lower.

Given we want to increase decentralization by increasing number of unique block producers, as well as maximize the amount at stake - we have discussed alternatives.

An alternative was suggested by @SkidanovAlex to determine number of seats dynamically, in such a way to get 100 unique block producers:
 - change threshold finding routine, to find 100-th smallest stake. And determine number of seats based on that.

The concerns voice previously:
 - Large validators can split their stake to push away smaller validators. Unclear why would they do, the economic incentive is small (we pay proportionally to stake, so if validator has 10x the stake, and pushes out 10 small stake validators - they only get a bit more of what this in rewards). This reduces decentralization though so they may get punished for that from their delegates. This is also not worth than current state.
 - If 100th validator has 1/1,000,000 of stake of the first one - the number of seats will be huge and the internals of EpochManager may take long time to calculate. This argument can be address by capping number of seats with some large but limiting number. Which means that if stake of lowest validators is so much smaller - they will be ignored.

**Comment by abacabadabacaba** [comment]
I think that we should eliminate the concept of seats entirely. Still, we should probably cap the ratio of the total stake of all validators to the stake of the smallest validator, but this cap should be higher (e.g. 1000 rather than 100).

**Comment by ilblackdragon** [comment]
@abacabadabacaba how would you eliminate the concept of seats? how do we predictably allocate validators for the next epoch without seats? or we do want to remove predictability and add randomness to the process?

**Comment by abacabadabacaba** [comment]
We sort proposed validators by their stake, and then add them, starting from the highest stake, until some threshold (which can be the number of validators, or the ratio of total stake to the current validator's stake, or something else). Regarding the assignment of validators to block heights, AFAIK it is already pseudo-random.

**Comment by ilblackdragon** [comment]
It's pseudo-random because we have seats - we duplicate each validator by number of seats they got and then we shuffle. And that defines the order for epoch ahead.

**Comment by abacabadabacaba** [comment]
We can pseudo-randomly compute validator to block height assignment as soon as the set of validators is determined. We can set the probability each validator is selected to be proportional to its stake. There is no need to have validator's weight to be measured in discrete "seats" for that.

**Comment by bowenwang1996** [comment]
@abacabadabacaba it seems that will create a scenario where some validator is selected but will not produce any block due to probability being low.

**Comment by abacabadabacaba** [comment]
If a validator's fraction of stake is less than what corresponds to one block, then it should be expected that such validator may not be assigned to any blocks. But producing blocks is not the only thing that validators do.

**Comment by SkidanovAlex** [comment]
If I understand the Evgeny's proposal correctly, I agree with it. Specifically,

1. Merge the concept of a validator seat and the validator (as in, each stake gets either exactly 1 or exactly 0 seats). Always choose top 100 stakes (but for example cut early if the ratio of the first stake and the last stake is too large).
2. Sample block producers and chunk producers at each height weighted by the stake (it can be done cheaply, e.g. by ordering block producers deterministically, and storing in the epoch manager sums of prefixes of their stakes, we can do weighted sampling in log(n)).

It doesn't solve the problem that stakers will split their stake though.

**Comment by mfornet** [comment]
> we can do weighted sampling in log(n)

Side comment in this discussion, you can sample from a finite, weighted random variable in O(1) with O(n) preprocessing and O(n) space. I can't find any link with explanation right now, but can explain if interested, though it is not very relevant for the discussion here.

**Comment by bowenwang1996** [comment]
> you can sample from a finite, weighted random variable in O(1) with O(n) preprocessing and O(n) space. I can't find any link with explanation right now, but can explain if interested, though it is not very relevant for the discussion here.

That sounds interesting. How does it work? Also what does the constant look like? Is it actually fast in practice?

**Comment by ilblackdragon** [comment]
@SkidanovAlex @k06a If light client verification on Ethereum can handle this - that sounds fine to me.

**Comment by abacabadabacaba** [comment]
@ilblackdragon I think that light clients don't need to do this computation. The only thing that light clients need to do is to check that an endorsement for a block is signed by more than 2/3 of the validators (weighted by stake) for the current epoch. That block should include the set of validators (their keys and stakes) for the next epoch. Light clients don't need to compute this set, only to check that it is included in a properly signed block. Also, light clients don't care which block producer is assigned to each specific height.

**Comment by ilblackdragon** [comment]
Now you are just blowing my mind :) But you are right.

Then we don't even need to know exact block producer way ahead, and can define it on the fly 1--3 blocks ahead (for timely chunks and transaction routing). E.g. based on randomness from block T, we can sample weighted which validator should produce T+2.

What do you think about this? Though I'm not sure it still has the same benefits for protecting against DDOS given block producer set is still small.

**Comment by bowenwang1996** [comment]
> we don't even need to know exact block producer way ahead

I think we still do because otherwise there will be no orphan sync and block sync will be even slower.

**Comment by ilblackdragon** [comment]
The point is that after block is produced, we don't care who produced it - if it has 2/3 of stake approvals on it. So all syncs / block acceptance code doesn't need to look at who produced it - can just check approvals.

**Comment by ilblackdragon** [comment]
Ok, additional thing we should do then - is stop counting number of _produced_ blocks for kickouts but instead count number of approvals signed. And may be account for _produced_ blocks in some additional sort.

**Comment by bowenwang1996** [comment]
>  So all syncs / block acceptance code doesn't need to look at who produced it - can just check approvals.

You still need to check the signature of the block and know whom to slash when things go wrong.

**Comment by birchmd** [comment]
@SkidanovAlex RE:

> or example cut early if the ratio of the first stake and the last stake is too large

I think the more relevant factor is the fraction of the total stake that the smallest stake represents. As far as I understand, the point of such a condition is to help ensure that if a validator is chosen as a block producer then they will actually get to make a block at some point during the epoch.  If we plan to sample from a distribution weighted by the stakes, then the probability that the smallest stake, `s_min`, is not chosen during an epoch consisting of `L` blocks is 

```
p = (1 - s_min / S)^L
```

where `S = \sum_i { s_i }` is the sum of all the block producer stakes.

So I think we should choose some tolerance for this probability and define the cut-off based on this tolerance. For example, if we require `p < 0.01` (i.e. less than 1% chance the smallest stake does not produce a block), then with an epoch length of `L = 43200`, the minimum stake fraction we could accept is `s_min / S = 0.00011 = 0.011%`. Computing the cut-off based on this condition is very easy; we sort the proposals by stake and compute the cumulative stake total as we go down the proposals (which we need anyways to do the random sampling later), stopping either when we hit the 100th proposal, or when `s_i / S` is too small.

**Comment by SkidanovAlex** [comment]
While it is true that there's a possibility we don't need to look far into the future, there's nothing that prevents us from implementing it in a way that we do see far into the future, and don't need to think about it :)

```
def get_block_producer(epoch, height):
    return determenistic_random_sample(seed = combine(epoch.random_seed, height), values = epoch.block_producers)

def get_chunk_producer(epoch, shard_id, height):
    return determenistic_random_sample(seed = combine(epoch.random_seed, shard_id, height), values = epoch.block_producers)
```

**Comment by SkidanovAlex** [comment]
(Though in a single shard system we want the property that the chunk producer for shard 0 at height `h` is the same as the block producer at height `h+1`, so some minor modifications are needed in the above routines to account for that)

**Comment by SkidanovAlex** [comment]
> So I think we should choose some tolerance for this probability and define the cut-off based on this tolerance. For example, if we require p < 0.01 (i.e. less than 1% chance the smallest stake does not produce a block), then with an epoch length of L = 43200, the minimum stake fraction we could accept is s_min / S = 0.00011 = 0.011%. Computing the cut-off based on this condition is very easy; we sort the proposals by stake and compute the cumulative stake total as we go down the proposals (which we need anyways to do the random sampling later), stopping either when we hit the 100th proposal, or when s_i / S is too small.

This sounds great

**Comment by birchmd** [comment]
@mfornet I am interested in the O(1) sampling algorithm. I am only aware of the O(log n) one.

**Comment by abacabadabacaba** [comment]
@birchmd TAOCP §3.4.1

**Comment by birchmd** [comment]
Thanks for the reference! Turns out it is already implemented in the `rand` crate anyways. https://rust-random.github.io/rand/rand/distributions/weighted/alias_method/struct.WeightedIndex.html

**Comment by birchmd** [comment]
@SkidanovAlex RE: selecting chunk producer

I don't think your suggestion

```
determenistic_random_sample(seed = combine(epoch.random_seed, shard_id, height), values = epoch.block_producers)
```

works because this will select from any of the block producers, which effectively means they are all assigned to any shard.

Instead, I think we should explicitly assign validators to each shard and then we can choose randomly from those (or simply cycle through them, depending on what we think is better). The question is how this assignment should be made. I think ideally we would want roughly equal stakes in all shards, so maybe the assignment scheme would be something like 

```rust
// Assume block_producers is sorted in decreasing order by stake.
// Return the shard_id each block producer is assigned to (in the same order as block_producers)
fn assign_shards(block_producers: &[ValidatorStake], num_total_shards: usize) -> Vec<ShardId> {
    let mut shard_stakes: BinaryHeap<(Balance, ShardId)> = iter::repeat(0)
        .enumerate()
        .take(num_total_shards)
        .map(|(id, stake)| (stake, id)) // swap order because we want sort to be over stake, then id
        .collect(); // this probably doesn't compile, but you get the point.
  
    let mut result = Vec::with_capacity(block_prodcers.len());
    for bp in block_producers {
        let (least_stake, shard_id) = shard_stakes.pop();
        result.push(shard_id);
        shard_stakes.push((least_stake + bp.stake, shard_id));
    }
   result
}
```

**Comment by birchmd** [comment]
I wrote up a more detailed spec of how I think seat selection should work, included choosing block producers from proposals, choosing a block producer to make each block at each height, and choosing a chunk producer for each shard at each height. Please feel free to review and comment.

https://docs.google.com/document/d/177zqbkbQkFanxfQ5GppDX4H5KLVUpcDckx5hes7yXZc/edit?usp=sharing

**Comment by bowenwang1996** [comment]
@birchmd please convert your google doc to a PR in this repo.

**Comment by birchmd** [comment]
https://github.com/nearprotocol/NEPs/pull/83

**Comment by ilblackdragon** [comment]
This has changed awhile ago.
