### ISSUE TITLE
[Proposal]  alt_bn128 curve math

### ISSUE THREAD

**Issue by snjax** [near/NEPs#98]
# Proposal

To implement a set of zkSNAKs verifiers (like Groth16 or PLONK) I suggest to add alt_bn128 math functions into VM:
To learn more about alt_bn128 and subgroups G1 and G2 see [EIP-196](https://eips.ethereum.org/EIPS/eip-196) and [EIP-197](https://eips.ethereum.org/EIPS/eip-197).

## Functions
All formulas below are defined in additive notation. If data is wrong serialized, the function returns Error.

* ### alt_bn128_g1_multiexp(items:&[G1, Fr]) -> Result\<G1\>
Compute ![\sum s_i g_i](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Csum%20s_i%20g_i) with [Pippenger's algorithm](https://github.com/wborgeaud/python-pippenger/blob/master/pippenger.pdf), where ![s_i](https://latex.codecogs.com/gif.latex?%5Cinline%20s_i) are Fr scalars and ![g_i](https://latex.codecogs.com/gif.latex?%5Cinline%20g_i) are G1 group elements.

Bad data: If a ![s_i](https://latex.codecogs.com/gif.latex?%5Cinline%20s_i) is more or equal then Fr order or ![g_i](https://latex.codecogs.com/gif.latex?%5Cinline%20g_i) is not in G1 group, function returns Error. 

Complexity: ![O(\frac{n}{\log(n))})](https://latex.codecogs.com/gif.latex?%5Cinline%20O%28%5Cfrac%7Bn%7D%7B%5Clog%28n%29%29%7D%29) . I propose to use regularization ![\frac{n}{\max(\log_2(n),1) )}](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cfrac%7Bn%7D%7B%5Cmax%28%5Clog_2%28n%29%2C1%29%20%29%7D) for ![n<=1](https://latex.codecogs.com/gif.latex?%5Cinline%20n%20%5Cleq%201).

Gas formula: 

```rust
fn log2floor(x:u64) -> u64 {
    let mut t = x;
    let mut r = 0;
    for offset in [32, 16, 8, 4, 2, 1].iter() {
        if t >> offset != 0 {
            t >>= offset;
            r += offset;
        }
    }
    r
}

let n = (n_bytes+item_size-1)/item_size;
let gas_consumed = A+B*n+C * if n > 1 {n / log2floor(n)} else {n};
```
`B` is linear component, corresponding to deserialization complexity. 

* ### alt_bn128_g1_sum(items:&[G1, bool]) -> Result\<G1\>

Compute ![\sum (-1)^{s_i} g_i](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Csum%20%28-1%29%5E%7Bs_i%7D%20g_i).

Bad data:  If a ![s_i](https://latex.codecogs.com/gif.latex?%5Cinline%20s_i) is not one or zero or ![g_i](https://latex.codecogs.com/gif.latex?%5Cinline%20g_i) is not in G1 group, function returns Error. 

Complexity: linear

Gas formula: 

```rust
let n = (n_bytes+item_size-1)/item_size;
let gas_consumed = A+B*n;
```

* ### alt_bn128_pairing_check(items:&[G1,G2]) -> Result\<bool\>

Compute ![\sum e(g_{1 i}, g_{2 i}) \stackrel{?}{=} 1](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Csum%20e%28g_%7B1%20i%7D%2C%20g_%7B2%20i%7D%29%20%5Cstackrel%7B%3F%7D%7B%3D%7D%201)

Bad data: If  ![g_1i](https://latex.codecogs.com/gif.latex?%5Cinline%20g_%7B1i%7D) is not in G1 group or ![g_2i](https://latex.codecogs.com/gif.latex?%5Cinline%20g_%7B2i%7D) is not in G2 subgroup, function returns Error. 

Complexity: linear

Gas formula: 

```rust
let n = (n_bytes+item_size-1)/item_size;
let gas_consumed = A+B*n;
```

## Data encoding

G1 is serialized as two U256 (x and y) in LE.
G2 is serialized as four U256 (re(x), im(x), re(y), im(y)) in LE.
bool is serialized as one byte.
Tuple is serialized as concatenated chunks of serialized elements.
Slice is serialized as concatenated chunks of serialized elements.

## Implementation

alt_bn128 functions implemented as fork of [parity-bn](https://github.com/paritytech/bn) with minor updates: 
* serialization, deserialization
* pippenger multiexp
* API, described above

The crate should be published and moved to [nearprotocol](https://github.com/nearprotocol).

**Comment by nearmax** [comment]
@akhi3030 Is this implemented and can be closed?

**Comment by akhi3030** [comment]
@nearmax: in https://github.com/near/nearcore/pull/6824, we stabalised `alt_bn128_g1_multiexp`, `alt_bn128_g1_sum`, `alt_bn128_pairing_check`.
However, I do not see any NEPs or spec for these function in this repo.  Maybe a NEP is not strictly necessary as the bulk of the work was done before the NEP process was standardised.  However, we should probably add something to the spec.  Should we keep this issue open till that work is done or should we create a different issue for that?

**Comment by frol** [comment]
@akhi3030 Yes, please, create a new issue and close this one. Could you take ownership of getting the spec updated? 🙏

**Comment by akhi3030** [comment]
> @akhi3030 Yes, please, create a new issue and close this one. Could you take ownership of getting the spec updated? 🙏

Happy to do so!

**Comment by akhi3030** [comment]
The remaining work is now tracked in https://github.com/near/NEPs/issues/426.  Please prefer continuing discussions on that issue.
